import {WEAPONS,HEAT,heatState,forgeSpot,resolveSmith} from './action-game.js?v=9';
export function installForgeUI({getPlayer,act,openDialog,onTalk,onUpdate,doc=document,clock=()=>Date.now()}){
 const $=id=>doc.getElementById(id);let smith=null,view='catalog',waiting=false,offset=0,raf,finished=null;
 const now=()=>clock()+offset;
 async function perform(action){if(waiting)return;waiting=true;paint();const start=clock();try{const r=await act(action);offset=r.player.updatedAt-(start+clock())/2;finished=r.extra.crafted||null;onUpdate?.();if(finished)view='catalog';render();$('forge-feedback').textContent=r.summary;return r;}catch(e){$('forge-feedback').textContent=e.message;}finally{waiting=false;render();}}
 function catalog(){const p=getPlayer();$('smith-wallet').textContent=`${p.coins} credits · ${p.inventory.iron} alloy fragments · ${p.inventory.wood} biomass · ${p.inventory.powerballs} Powerballs`;$('forge-catalog').replaceChildren();
  for(const r of WEAPONS){const card=doc.createElement('article');card.className='weapon-card';const title=doc.createElement('h3');title.textContent=r.name;const desc=doc.createElement('p');desc.textContent=r.description;const stats=doc.createElement('small');stats.textContent=`${r.damage} damage · ${r.hits} strikes · 2 seconds per mark`;const cost=doc.createElement('p');cost.className='forge-cost';cost.textContent=`Bay rental ${r.fee} credits · ${r.iron} alloy fragments · ${r.wood} biomass`;const button=doc.createElement('button');button.className='primary';button.textContent=`Rent bay & fabricate · ${r.fee} credits`;button.disabled=waiting||!!p.forge||p.coins<r.fee||p.inventory.iron<r.iron||p.inventory.wood<r.wood;button.onclick=async()=>{view='work';const result=await perform({type:'forge-start',target:smith.id,recipe:r.id});if(!result)view='catalog';render();};card.append(title,desc,stats,cost,button);$('forge-catalog').append(card);}
  $('forge-resume').hidden=!p.forge;$('forge-resume').disabled=waiting||p.forge?.smith!==smith.id;$('forge-resume').textContent=p.forge?.smith!==smith.id&&p.forge?`Blank waiting with ${resolveSmith(p.forge.smith)?.name||'another fabricator'}`:'Resume paid blank';$('smith-buy').disabled=waiting||p.coins<8;$('refine-powerball').disabled=waiting||p.inventory.stone<2||p.inventory.iron<1;
  for(const button of $('smith-trades').querySelectorAll('[data-kind]'))button.disabled=waiting||p.inventory[button.dataset.kind]<(button.dataset.kind==='powerballs'?1:5);
  $('forge-result').hidden=!finished;$('forge-result').textContent=finished?`${finished.name} fabricated and equipped.`:'';
 }
 function render(){if(!smith)return;const p=getPlayer(),job=p.forge;$('forge-dialog').classList.toggle('forge-playing',view==='work');$('smith-title').textContent=`${smith.name} · Fabricator of ${smith.village}`;$('smith-catalog-view').hidden=view!=='catalog';$('forge-work-view').hidden=view==='catalog';if(view==='catalog'){catalog();return;}if(!job){view='catalog';catalog();render();return;}
  const r=WEAPONS.find(w=>w.id===job.recipe);$('forge-weapon-name').textContent=r.name;$('forge-progress').textContent=`${job.step}/${r.hits} strikes · ${job.mistakes}/3 mistakes`;
  const ruined=job.phase==='failed'||job.phase==='heat'&&heatState(job,now()).ruined;$('forge-heating').hidden=job.phase!=='heat'||ruined;$('forge-hammering').hidden=job.phase!=='hammer'||ruined;$('forge-ruined').hidden=!ruined;
  if(job.phase==='hammer'){const spot=forgeSpot(job);for(const [i,b]of [...$('forge-grid').children].entries()){b.classList.toggle('lit',i===spot);b.textContent=i===spot?'Strike here':String(i+1);b.setAttribute('aria-label',i===spot?`Strike highlighted spot ${i+1}`:`Press spot ${i+1}`);b.disabled=waiting;}}
  $('forge-retry').disabled=waiting;$('forge-abandon').disabled=waiting;paint();
 }
 function paint(){if(view!=='work'||!smith||!$('forge-dialog').open)return;const job=getPlayer().forge;if(!job)return;
  if(job.phase==='heat'){const state=heatState(job,now());$('heat-needle').style.left=`${state.level}%`;$('heat-billet').style.setProperty('--heat-color',state.ready?'#ff9b32':state.elapsed>HEAT.orangeEnd?'#ffe5ac':state.elapsed>3000?'#db4a29':'#63716c');$('heat-billet').classList.toggle('glowing',state.elapsed>3000);$('heat-label').textContent=state.ruined?'Sparks and fizzle — the blank broke apart!':state.ready?'Orange-hot. Move it to the forming press now!':state.elapsed>HEAT.orangeEnd?'Too hot. The metal is losing strength!':state.elapsed>3000?'Cherry red. Keep heating…':'Cold alloy. Induction coils are heating it…';$('forge-transfer').disabled=waiting||!state.ready;if(state.ruined&&!$('forge-heating').hidden)render();}
  if(job.phase==='hammer'){const left=Math.max(0,job.deadline-now());$('strike-countdown').textContent=`${(left/1000).toFixed(1)} s`;$('strike-timer').value=left/2000*100;if(!left&&!waiting)perform({type:'forge-strike',step:job.step,spot:-1});}
 }
 function tick(){paint();raf=requestAnimationFrame(tick);}tick();
 $('forge-transfer').onclick=()=>perform({type:'forge-transfer'});$('forge-retry').onclick=()=>perform({type:'forge-retry'});$('forge-abandon').onclick=()=>perform({type:'forge-abandon'});$('forge-resume').onclick=()=>{view='work';render();};$('forge-back').onclick=()=>{view='catalog';render();};$('refine-powerball').onclick=()=>perform({type:'refine-powerball',target:smith.id});$('smith-buy').onclick=()=>perform({type:'smith-buy',target:smith.id});
 for(const b of $('smith-trades').querySelectorAll('[data-kind]'))b.onclick=()=>perform({type:'smith-sell',target:smith.id,kind:b.dataset.kind});
 for(let i=0;i<9;i++){const b=doc.createElement('button');b.type='button';b.textContent=i+1;b.onclick=()=>{const job=getPlayer().forge;if(job?.phase==='hammer'){const hit=i===forgeSpot(job);$('forge-grid').classList.remove('hit','miss');void $('forge-grid').offsetWidth;$('forge-grid').classList.add(hit?'hit':'miss');perform({type:'forge-strike',step:job.step,spot:i});}};$('forge-grid').append(b);}
 const key=e=>{if(!$('forge-dialog').open||view!=='work'||waiting)return;if(/^[1-9]$/.test(e.key)&&getPlayer().forge?.phase==='hammer'){e.preventDefault();$('forge-grid').children[+e.key-1].click();}if(e.code==='Space'&&getPlayer().forge?.phase==='heat'){e.preventDefault();if(!$('forge-transfer').disabled)$('forge-transfer').click();}};doc.addEventListener('keydown',key);
 $('smith-talk').onclick=()=>{$('forge-dialog').close();onTalk(smith);};
 return {open(s){smith=s;finished=null;view='catalog';$('forge-feedback').textContent='';render();openDialog('forge-dialog');},refresh(){if(smith&&$('forge-dialog').open)render();},destroy(){cancelAnimationFrame(raf);doc.removeEventListener('keydown',key);}};
}
