export const RESOURCE_NAMES={wood:'Biomass',stone:'Silicate',berries:'Nutrient pods',fiber:'Biofilament',iron:'Alloy fragments',powerballs:'Powerballs'};
export const ROLE_TITLES={gatherer:'Scavenger',keeper:'Colony steward',wayfarer:'Freight runner',smith:'Fabricator',pilot:'Skiff pilot'};
export const LORE=[
 {id:'fringe',title:'Outside the public routes',text:'The Fringe is the cluster of star systems beyond the Beshtala-Chanko public transit routes. No legal or political authority governs it. Corporations, faiths, criminal ventures, and independent prospectors all try to make something of its unincorporated worlds.'},
 {id:'powerballs',title:'The Powerball boom',text:"Man Earlie’s Expeditionary Society discovered Powerballs on Earlie Prime. Demand for this powerful energy source in Beshtala-Chanko turned Earlie’s harvesting and refining operation into the Round Power Corporation. Dugall Freight helped establish its first shipping routes."},
 {id:'wars',title:'The Freight Wars',text:'Round Power demanded exclusive transport rights. Dugall wanted to carry other private ventures into the frontier. Earlie recruited asteroid rustlers and sent their agile skiffs against Dugall freighters. They developed an EVA combat style that used mining equipment to disable reactors and strand cargo and passengers.'},
 {id:'feigngull',title:'The Feigngull Massacre',text:'The Maven reported that Earlie’s rustlers had evacuated the entire passenger cabin in the Feigngull Massacre. Money and support from Beshtala-Chanko began flowing to Dugall. The growing conflict brought infrastructure and migrants into The Fringe even while it tore freighters apart.'},
 {id:'earlie',title:'Earlie’s fragmented army',text:'Earlie made changing alliances to serve immediate needs. His Fringeling Army became a sprawling mix of interests, known for internal conflict, tactical savagery, and unpredictable moves. Some saw desperate improvisation; others saw deliberate chaos. That eclectic army helped seed the frontier’s cultural diversity.'},
 {id:'klem',title:'Klem opens the floodgates',text:'Man Earlie fought until his death. His family cited infection; loyalists and Freight Wars revivalists still circulate other accounts. His daughter, Klem Earlie, took over Round Power, disbanded the corporate army, and ended the attacks. The Freight Wars ended, and access to The Fringe expanded.'},
 {id:'today',title:'A frontier of human experiments',text:'As the Powerball boom cooled, expeditions and corporate speculation pushed freight lines to more planets. Profiteers, outlaws, ideological communities, political outcasts, and displaced peoples followed. The Fringe remains a dangerous part of the Occupied Spaces, drawing migrants with freedom, opportunity, and the possibility of escape.'},
 {id:'drifters',title:'Drifter colonies · field notes',text:'In this game, Drifters are the people making lives on these worlds: scavengers, freight runners, fabricators, and colony stewards. They repurpose cargo hulls and old infrastructure into settlements. A landing pod is your first home. Colony beacons connect you to private transit; abandoned industrial sites still hold supplies and active security units.'}
];
export function loreReply(message){const q=message.toLowerCase();if(/feigngull|massacre|maven/.test(q))return LORE[3].text;if(/klem|daughter|death|infection|patricide/.test(q))return LORE[5].text;if(/fringeling|army|rustler|eva/.test(q))return LORE[4].text;if(/freight war|wars|dugall|exclusive/.test(q))return LORE[2].text;if(/earlie|round power|powerball|boom/.test(q))return LORE[1].text;if(/beshtala|chanko|law|government|fringe|history/.test(q))return LORE[0].text;if(/drifter|coloniz|colonis|colonist/.test(q))return LORE[7].text;return null;}

export function containsPowerball(node){return node.kind==='stone'&&((Math.floor(node.x)*13+Math.floor(node.z)*7)%5+5)%5===0;}
