import {Store} from './storage.js';
import {WorldRenderer} from './render.js';
import {drawMap} from './map.js';
import {BIOMES,CHUNK,REGION,LIMIT,SEED,biomeAt,nearestSettlement,settlement,waterDistance} from './world.js';
const $=id=>document.getElementById(id);let store=new Store(),world,player,nearby=null,busy=false,dirty=false,activeNpc=null,waypoint=null,miniLast={x:Infinity,z:Infinity,time:0},events=[],mapSpan=2600,mapCenter=null,saveTimer,loaded=false;
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),4300);}
function status(message){$('save-status').textContent=message;}
function openDialog(id){$(''+id).showModal();if(world)world.keys={};}
function updateUI(){if(!player)return;$('health').value=player.health;$('food').value=player.food;$('water').value=player.water;$('berry-count').textContent=player.inventory.berries;$('account-name').textContent=player.name;$('rename-input').value=player.name;}
function chunks(){const out=[];const cx=Math.floor(world.player.x/CHUNK),cz=Math.floor(world.player.z/CHUNK);for(let x=cx-2;x<=cx+2;x++)for(let z=cz-2;z<=cz+2;z++)out.push([x,z]);return out;}
async function sync(){if(!loaded||busy||dirty)return;try{const result=await store.request('state',{chunks:chunks()});world.setDepleted(result.depleted);world.setOthers(result.players||[]);events=result.events||events;if(result.player.revision>player.revision){player=result.player;world.setPlayer(player);updateUI();toast('Your traveler was updated from another session.');}}catch(e){status('Connection interrupted');}}
async function flush(){if(!world||!dirty||busy)return;busy=true;status('Saving footsteps');const pos={x:world.player.x,z:world.player.z};try{const result=await store.action({type:'move',...pos},player);player=result.player;dirty=Math.hypot(world.player.x-pos.x,world.player.z-pos.z)>.05;updateUI();status(store.mode==='local'?'Saved on this device':'World saved');}catch(e){status('Save failed');toast(e.message);if(/too far|Deep water|another session|revision|conflict/i.test(e.message)){await restorePosition();} }finally{busy=false;}}
async function restorePosition(){try{const state=await store.request('state',{chunks:chunks()});player=state.player;world.setPlayer(player);dirty=false;world.target=null;updateUI();}catch{}}
async function waitForSave(){await flush();if(busy)throw Error('Your footsteps are still saving. Try again in a moment.');if(dirty){await flush();if(dirty)throw Error('Save your position before interacting.');}}
async function act(action){try{await waitForSave();busy=true;status('Saving');const result=await store.action(action,player);player=result.player;world.player={...world.player,...player,x:world.player.x,z:world.player.z};if(result.depleted)world.setDepleted(result.depleted);else if(action.type==='gather')world.setDepleted([...world.depleted,action.target]);updateUI();status(store.mode==='local'?'Saved on this device':'World saved');if(action.type!=='talk')toast(result.summary);return result;}catch(e){toast(e.message);status('Action not saved');throw e;}finally{busy=false;}}
function frame({x,z,moved,dt}){if(!loaded)return;if(moved)dirty=true;
 if(Date.now()-(frame.uiTime||0)<220)return;frame.uiTime=Date.now();nearby=world.closest();const s=nearestSettlement(x,z),biome=BIOMES[biomeAt(x,z)].name;
 $('location').textContent=s.distance<75?s.name:biome;$('biome').textContent=biome;$('coords').textContent=`${Math.round(x)}, ${Math.round(z)}`;
 $('interact-button').disabled=!nearby||busy;$('interact-button').innerHTML=nearby?(nearby.type==='npc'?`Talk to ${nearby.name}`:`Gather ${nearby.kind}`)+' <kbd>E</kbd>':'Explore <kbd>E</kbd>';
 let tip=nearby?(nearby.type==='npc'?`${nearby.name} · ${nearby.role}`:`${nearby.kind[0].toUpperCase()+nearby.kind.slice(1)} within reach`):s.distance<60?`${s.name} · a place to rest`:'The wilderness is yours to explore';
 if(waypoint&&!nearby){const distance=Math.round(Math.hypot(waypoint.x-x,waypoint.z-z));tip=`Waypoint · ${distance} m away`;if(distance<10){waypoint=null;toast('You reached your waypoint.');}}
 $('nearby-tip').textContent=tip;$('drink-button').disabled=busy||(s.distance>48&&waterDistance(x,z)>27);$('rest-button').disabled=busy||s.distance>60;$('eat-button').disabled=busy||player.inventory.berries<1;
 if(Date.now()-miniLast.time>6000||Math.hypot(x-miniLast.x,z-miniLast.z)>35){drawMap($('minimap'),{x,z},640,{x,z},{waypoint,visited:player.visited});miniLast={x,z,time:Date.now()};}
}
function walk(pos){if(!loaded||document.querySelector('dialog[open]'))return;if(!world.passable(pos.x,pos.z)){toast('Deep water. Follow a road to find a bridge.');return;}world.target=pos;}
async function interact(){if(!nearby||busy)return;if(nearby.type==='resource'){act({type:'gather',target:nearby.id}).catch(()=>{});}else{activeNpc=nearby;$('npc-name').textContent=nearby.name;$('npc-role').textContent=`${nearby.role} of ${nearby.village}`;$('npc-avatar').textContent=nearby.name[0];$('conversation').replaceChildren();$('memory-count').textContent='Loading memory';openDialog('talk-dialog');try{const r=await store.request('memory',{npc:nearby.id});showMemories(r.memories||[]);}catch(e){toast(e.message);$('memory-count').textContent='Memory unavailable';}}}
function bubble(name,message,you=false){const b=document.createElement('div');b.className='bubble'+(you?' you':'');const label=document.createElement('small');label.textContent=name;b.append(label,document.createTextNode(message));$('conversation').append(b);$('conversation').scrollTop=$('conversation').scrollHeight;}
function showMemories(memories){$('conversation').replaceChildren();const mine=memories.filter(m=>m.playerId===player.id);$('memory-count').textContent=`${memories.length} remembered exchanges`;
 if(!mine.length)bubble(activeNpc.name,`Welcome to ${activeNpc.village}. I'm ${activeNpc.name}. What would you like me to know?`);
 else{bubble(activeNpc.name,`Welcome back, ${player.name}. I remember our conversations.`);for(const m of mine.slice(-15)){bubble(m.playerName||player.name,m.message,true);bubble(activeNpc.name,m.response);}}
}
function showPack(){const inv=$('inventory');inv.replaceChildren();for(const [kind,symbol]of Object.entries({wood:'▥',stone:'◆',berries:'●',fiber:'≋'})){const item=document.createElement('div'),icon=document.createElement('span'),name=document.createElement('span'),count=document.createElement('b');icon.className='item-icon';icon.textContent=symbol;name.textContent=kind[0].toUpperCase()+kind.slice(1);count.textContent=player.inventory[kind];item.append(icon,name,count);inv.append(item);}
 $('journey-summary').textContent=`${player.visited.length} settlements visited · ${(player.distance/1000).toFixed(2)} km walked`;
 $('journal').replaceChildren();for(const e of events.filter(e=>e.type!=='move').slice(0,10)){const d=document.createElement('div');d.className='journal-entry';d.textContent=e.summary;const t=document.createElement('small');t.textContent=new Date(e.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});d.append(t);$('journal').append(d);}if(!$('journal').childNodes.length)$('journal').textContent='Your story is just beginning.';openDialog('pack-dialog');}
function redrawMap(){if(!mapCenter)mapCenter={x:world.player.x,z:world.player.z};drawMap($('atlas'),mapCenter,mapSpan,world.player,{detailed:true,waypoint,visited:player.visited});$('map-scale').textContent=`${(mapSpan/1000).toFixed(1)} km across`;}
async function loadWorld(){status('Opening save');const result=await store.request('state');player=result.player;events=result.events||[];world.setPlayer(player);world.setDepleted(result.depleted||[]);world.setOthers(result.players||[]);loaded=true;updateUI();$('loading').hidden=true;status(store.mode==='local'?'Saved on this device':'World saved');
 if(store.mode==='local'){$('connection-notice').hidden=false;$('local-options').hidden=false;$('storage-explanation').textContent='Local preview: your save and NPC conversations are stored only in this browser. Shared world and account saves need the backend connection.';}else{$('storage-explanation').textContent='Your traveler is saved in the shared world. Sign in with the same account on another device to continue.';$('signout-button').hidden=store.mode==='local';}
 if(player.revision===0){const s=nearestSettlement(player.x,player.z);$('welcome-village').textContent=s.name;$('traveler-name').value=player.name==='Traveler'?'':player.name;openDialog('welcome');}
 clearInterval(saveTimer);saveTimer=setInterval(flush,2000);setInterval(sync,6500);
}
async function boot(){try{world=new WorldRenderer($('scene'),{onWalk:walk,onFrame:frame});await store.init();if(!store.signedIn){$('loading').hidden=true;openDialog('auth-dialog');return;}await loadWorld();}catch(e){$('loading-text').textContent=e.message;const b=document.createElement('button');b.textContent='Try again';b.onclick=()=>location.reload();$('loading').append(b);}}
$('begin-button').onclick=async()=>{try{await act({type:'rename',name:$('traveler-name').value||'Traveler'});$('welcome').close();toast('Welcome to Evermere. Follow a road, or make your own way.');}catch{}};
$('interact-button').onclick=interact;$('eat-button').onclick=()=>act({type:'eat'}).catch(()=>{});$('drink-button').onclick=()=>act({type:'drink'}).catch(()=>{});$('rest-button').onclick=()=>act({type:'rest'}).catch(()=>{});
$('pack-button').onclick=async()=>{await sync();showPack();};$('map-button').onclick=()=>{mapCenter={x:world.player.x,z:world.player.z};openDialog('map-dialog');redrawMap();};$('account-button').onclick=()=>openDialog('account-dialog');
$('map-minus').onclick=()=>{mapSpan=Math.min(18000,mapSpan*1.5);redrawMap();};$('map-plus').onclick=()=>{mapSpan=Math.max(650,mapSpan/1.5);redrawMap();};$('map-center').onclick=()=>{mapCenter={x:world.player.x,z:world.player.z};redrawMap();};
$('atlas').onclick=e=>{const c=$('atlas'),r=c.getBoundingClientRect();waypoint={x:Math.max(-LIMIT,Math.min(LIMIT,mapCenter.x+((e.clientX-r.left)/r.width-.5)*mapSpan)),z:Math.max(-LIMIT,Math.min(LIMIT,mapCenter.z+((e.clientY-r.top)/r.height-.5)*mapSpan*c.height/c.width))};redrawMap();$('map-caption').textContent=`Waypoint set: ${Math.round(waypoint.x)}, ${Math.round(waypoint.z)}. Close the map and explore toward it.`;};
$('chat-form').onsubmit=async e=>{e.preventDefault();if(!activeNpc||busy)return;const message=$('chat-input').value.trim();if(!message)return;$('send-button').disabled=true;try{const r=await act({type:'talk',target:activeNpc.id,message});bubble(player.name,message,true);bubble(activeNpc.name,r.extra.response);$('chat-input').value='';const n=+(($('memory-count').textContent||'0').split(' ')[0]);$('memory-count').textContent=`${n+1} remembered exchanges`;}catch{}finally{$('send-button').disabled=false;}};
$('rename-button').onclick=()=>act({type:'rename',name:$('rename-input').value}).catch(()=>{});$('quality-button').onclick=()=>{const q=world.setQuality();$('quality-button').textContent='Quality: '+q;};
$('export-button').onclick=async()=>{try{await waitForSave();const a=document.createElement('a'),url=URL.createObjectURL(new Blob([store.exportLocal()],{type:'application/json'}));a.href=url;a.download='evermere-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){toast(e.message);}};
$('import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>10*1024*1024){toast('This save file is too large.');return;}try{store.importLocal(await f.text());location.reload();}catch(e){toast(e.message);}};
async function authenticate(signup=false){$('auth-error').textContent='';const email=$('email').value,password=$('password').value;if(!$('auth-form').reportValidity())return;$('login-button').disabled=$('signup-button').disabled=true;try{const session=await store.login(email,password,signup);if(!session){$('auth-error').textContent='Check your email to confirm your account, then sign in.';return;}$('auth-dialog').close();$('loading').hidden=false;await loadWorld();}catch(e){$('auth-error').textContent=e.message;}finally{$('login-button').disabled=$('signup-button').disabled=false;}}
$('auth-form').onsubmit=e=>{e.preventDefault();authenticate();};$('signup-button').onclick=()=>authenticate(true);$('signout-button').onclick=async()=>{try{await waitForSave();await store.logout();location.reload();}catch(e){toast(e.message);}};
window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName)||document.querySelector('dialog[open]')||!loaded)return;if(e.code==='KeyE')interact();if(e.code==='KeyI')showPack();if(e.code==='KeyM')$('map-button').click();});
window.addEventListener('visibilitychange',()=>{if(document.hidden){world.keys={};flush();}});window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}});
// Progressive WebMCP support shares the visible game's actions and authorization.
const ctx=document.modelContext;if(ctx?.registerTool){const life=new AbortController();for(const tool of [
 {name:'read_traveler',description:'Read current traveler, nearby interaction, and persistence mode.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({player,nearby:nearby?{id:nearby.id,type:nearby.type}:null,mode:store.mode})},
 {name:'gather_nearby_resource',description:'Gather the resource within reach and save the action.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async()=>{if(!nearby||nearby.type!=='resource')throw Error('No resource within reach.');const r=await act({type:'gather',target:nearby.id});return {summary:r.summary,inventory:player.inventory};}},
 {name:'speak_to_nearby_npc',description:'Send a message to the NPC within reach, saving it in their persistent memory.',inputSchema:{type:'object',properties:{message:{type:'string',minLength:1,maxLength:800}},required:['message'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(typeof input?.message!=='string'||!input.message.trim()||input.message.length>800)throw Error('Write a message of 1–800 characters.');if(!nearby||nearby.type!=='npc')throw Error('No person within reach.');const r=await act({type:'talk',target:nearby.id,message:input.message});return {response:r.extra.response,saved:true};}}
]){try{Promise.resolve(ctx.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>life.abort(),{once:true});}
boot();
