import {Store} from './storage.js?v=2';
import {WorldRenderer} from './render.js?v=3';
import {drawMap,drawCaveMap,drawMiniMap} from './map.js?v=3';
import {BIOMES,CHUNK,LIMIT,biomeAt,nearestSettlement,waterDistance} from './world.js';
import {caveStatus,roomAt,resolveDungeon} from './dungeons.js?v=2';
import {npcGreeting} from './rules.js?v=2';
const $=id=>document.getElementById(id);
let store=new Store(),world,player,nearby=null,busy=false,dirty=false,activeNpc=null,waypoint=null,miniLast={x:Infinity,z:Infinity,time:0},events=[],mapSpan=2600,mapCenter=null,saveTimer,syncTimer,loaded=false,trail=[],historyOffset=0,entrance=null,suppressed=new Set();
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),4300);}
function status(message){$('save-status').textContent=message;}
function openDialog(id){$(id).showModal();if(world)world.keys={};}
function saved(){status(store.mode==='local'?'Saved on this device':'World saved');}
function updateUI(){if(!player)return;$('health').value=player.health;$('food').value=player.food;$('water').value=player.water;$('berry-count').textContent=player.inventory.berries;$('account-name').textContent=player.name;$('rename-input').value=player.name;$('home-description').textContent=`Your cottage in ${player.house.villageName}. Each time you return to Evermere, you start at its doorstep.`;}
function chunks(){const out=[];const cx=Math.floor(player.x/CHUNK),cz=Math.floor(player.z/CHUNK);for(let x=cx-2;x<=cx+2;x++)for(let z=cz-2;z<=cz+2;z++)out.push([x,z]);return out;}
function applySnapshot(result,position=false){world.setDepleted(result.depleted||[]);world.setOthers(result.players||[]);if(result.homes)world.setHomes(result.homes);events=result.events||events;if(position){player=result.player;world.setPlayer(player);updateUI();}}
async function sync(){if(!loaded||busy||dirty)return;try{const r=await store.request('state',{chunks:chunks()});applySnapshot(r);if(r.player.revision>player.revision){player=r.player;world.setPlayer(player);trail=[];updateUI();toast('Your traveler was updated from another session.');}}catch{status('Connection interrupted');}}
async function flush(){
 if(!world||!dirty||busy)return;busy=true;status('Saving footsteps');const pos={x:world.player.x,z:world.player.z},sentTrail=trail.slice(0,80),used=sentTrail.length;
 try{const r=await store.action({type:'move',...pos,space:player.dungeon?.id||'overworld',trail:sentTrail},player);player=r.player;trail.splice(0,used);dirty=Math.hypot(world.player.x-pos.x,world.player.z-pos.z)>.05;world.exploration=player.caves;updateUI();saved();}
 catch(e){status('Save failed');toast(e.message);if(/too far|Deep water|wall|another session|revision|conflict|location changed/i.test(e.message))await restorePosition();}
 finally{busy=false;}
}
async function restorePosition(){try{const r=await store.request('state',{chunks:chunks()});player=r.player;world.setPlayer(player);applySnapshot(r);dirty=false;trail=[];}catch{}}
async function waitForSave(){await flush();if(busy)throw Error('Your footsteps are still saving. Try again in a moment.');if(dirty){await flush();if(dirty)throw Error('Save your position before interacting.');}}
async function act(action){
 try{await waitForSave();busy=true;status('Saving');const previousSpace=player.dungeon?.id,pos={x:world.player.x,z:world.player.z};const r=await store.action(action,player);player=r.player;
  if(previousSpace!==player.dungeon?.id||action.type==='return-home'){world.setPlayer(player);trail=[];dirty=false;miniLast.time=0;}
  else{world.player={...world.player,...player,...pos,dungeon:player.dungeon?{...player.dungeon,...pos}:null};world.exploration=player.caves;world.setHomes((world.homeList||[player.house]).map(h=>h.owner===player.id?player.house:h));}
  if(r.depleted)world.setDepleted(r.depleted);else if(action.type==='gather')world.setDepleted([...world.depleted,action.target]);updateUI();saved();
  events.unshift({id:crypto.randomUUID(),type:action.type,summary:r.summary,createdAt:Date.now()});if(action.type!=='talk')toast(r.summary);return r;
 }catch(e){toast(e.message);status('Action not saved');throw e;}finally{busy=false;}
}
function frame({x,z,moved}){
 if(!loaded)return;if(moved){dirty=true;const last=trail.at(-1)||player.dungeon||player;if(Math.hypot(x-last.x,z-last.z)>=.7)trail.push({x,z});}
 if(moved||Date.now()-miniLast.time>350){drawMiniMap($('minimap'),{...player,x,z,dungeon:player.dungeon?{...player.dungeon,x,z}:null},{cave:world.cave,depleted:world.depleted,waypoint,heading:world.hero.rotation.y});miniLast={x,z,time:Date.now()};}
 if(Date.now()-(frame.uiTime||0)<220)return;frame.uiTime=Date.now();nearby=world.closest();
 const cave=world.cave,s=cave?null:nearestSettlement(x,z),biome=cave?cave.dungeonName:BIOMES[biomeAt(x,z)].name;
 $('location').textContent=cave?cave.dungeonName:s.distance<90?s.name:biome;$('biome').textContent=cave?'Underground':biome;$('coords').textContent=cave?'A way back is never far':`${Math.round(x)}, ${Math.round(z)}`;
 const labels={npc:()=>`Talk to ${nearby.name}`,resource:()=>`Gather ${nearby.label||nearby.kind}`,entrance:()=>`Explore ruins`,exit:()=>`Leave dungeon`,home:()=>`Rest at home`};
 $('interact-button').disabled=!nearby||busy;$('interact-button').textContent=nearby?labels[nearby.type]():'Explore';const key=document.createElement('kbd');key.textContent='E';$('interact-button').append(key);
 let tip=cave?'Follow the passages. Find what the old stones hide.':s.distance<90?`${s.name} · a place to rest`:'The wilderness is yours to explore';
 if(nearby)tip=nearby.type==='npc'?`${nearby.name} · ${nearby.role}`:nearby.type==='resource'?`${nearby.label||nearby.kind} within reach`:nearby.type==='entrance'?nearby.name:nearby.type==='exit'?'The stair leads back to daylight':`${player.name}'s cottage`;
 if(waypoint&&!nearby&&!cave){const distance=Math.round(Math.hypot(waypoint.x-x,waypoint.z-z));tip=`Waypoint · ${distance} m away`;if(distance<10){waypoint=null;toast('You reached your waypoint.');}}
 $('nearby-tip').textContent=tip;$('secondary-tip').textContent=cave?'Click to navigate passages · E to gather · M for dungeon map':'WASD to move · scroll to zoom · drag to orbit';
 $('drink-button').disabled=busy||!!cave||s.distance>48&&waterDistance(x,z)>27;$('rest-button').disabled=busy||!!cave||s.distance>85&&Math.hypot(x-player.house.x,z-player.house.z)>14;$('eat-button').disabled=busy||player.inventory.berries<1;
 $('dungeon-status').hidden=!cave;if(cave){const room=roomAt(cave,x,z),progress=caveStatus(cave.id,player,world.depleted);$('dungeon-room').textContent=room===null?'The connecting passages':cave.rooms[room].name;$('dungeon-progress').textContent=`${progress.rooms}/${progress.totalRooms} chambers explored · ${progress.total-progress.collected} supplies remain`;}
 if(!cave){for(const id of [...suppressed]){const r=resolveDungeon(id);if(r&&Math.hypot(r.x-x,r.z-z)>22)suppressed.delete(id);}if(nearby?.type==='entrance'&&!suppressed.has(nearby.id)&&!busy&&!document.querySelector('dialog[open]'))showEntrance(nearby);}
}
function walk(pos){if(!loaded||document.querySelector('dialog[open]'))return;if(!world.passable(pos.x,pos.z)){toast(world.cave?'A stone wall blocks the way.':'Deep water. Follow a road to find a bridge.');return;}if(!world.setWalkTarget(pos))toast('There is no passage to that spot.');}
function showEntrance(target){entrance=target;const leaving=target.type==='exit';if(!leaving)suppressed.add(target.id);$('entrance-eyebrow').textContent=leaving?'Back toward daylight':'Beneath the old stones';$('entrance-title').textContent=leaving?'Return to the surface?':target.name;
 $('entrance-description').textContent=leaving?'The stone stair rises toward the ruined arch above. Your discoveries and gathered supplies will stay with you.':`Cool air rises from a stair beneath the broken arch. Beyond it lies ${target.dungeonName.toLowerCase()}. Will you descend?`;
 const id=leaving?player.dungeon.id:target.id,progress=caveStatus(id,player,world.depleted);$('entrance-stats').replaceChildren();
 for(const [name,value]of [['Exploration',progress.explored?'All chambers explored':progress.entered?`${progress.rooms}/${progress.totalRooms} chambers explored`:'Never entered'],['Supplies',progress.cleared?'All resources gathered':`${progress.total-progress.collected} deposits remain`]]){const div=document.createElement('div'),b=document.createElement('b'),span=document.createElement('span');b.textContent=name;span.textContent=value;div.append(b,span);$('entrance-stats').append(div);}
 $('entrance-warning').textContent=leaving?'You can return through these ruins whenever you wish.':'Take provisions. The stairs in the threshold chamber lead back outside.';$('enter-button').textContent=leaving?'Leave dungeon':'Enter dungeon';$('stay-button').textContent=leaving?'Keep exploring':'Stay outside';openDialog('entrance-dialog');
}
async function interact(){if(!nearby||busy)return;if(nearby.type==='resource'){act({type:'gather',target:nearby.id}).catch(()=>{});return;}if(nearby.type==='entrance'||nearby.type==='exit'){showEntrance(nearby);return;}if(nearby.type==='home'){act({type:'rest'}).catch(()=>{});return;}
 activeNpc=nearby;$('npc-name').textContent=nearby.name;$('npc-role').textContent=`${nearby.role} of ${nearby.village}`;$('npc-avatar').textContent=nearby.name[0];$('npc-stage').textContent={gatherer:`${nearby.name} brushes a leaf from a sleeve and looks up.`,keeper:`${nearby.name} pauses beside the well, listening.`,wayfarer:`${nearby.name} rests a travel-worn pack on the ground.`}[nearby.role];$('chat-input').value='';$('conversation').replaceChildren();openDialog('talk-dialog');showLine(npcGreeting(activeNpc,player,false));
 try{const r=await store.request('memory',{npc:nearby.id,personal:true});showLine(npcGreeting(activeNpc,player,r.memories.length>0));}catch(e){toast(e.message);}
}
function appendBubble(container,name,message,you=false){const b=document.createElement('div');b.className='bubble'+(you?' you':'');const label=document.createElement('small');label.textContent=name;b.append(label,document.createTextNode(message));container.append(b);return b;}
function showLine(message){$('conversation').replaceChildren();appendBubble($('conversation'),activeNpc.name,message);}
async function speak(message){if(!activeNpc||busy||!message.trim())return;$('send-button').disabled=true;for(const b of $('dialogue-choices').children)b.disabled=true;try{const r=await act({type:'talk',target:activeNpc.id,message});showLine(r.extra.response);$('chat-input').value='';}catch{}finally{$('send-button').disabled=false;for(const b of $('dialogue-choices').children)b.disabled=false;}}
async function loadHistory(reset=false){if(reset){historyOffset=0;$('history-content').replaceChildren();$('history-title').textContent=`Conversations with ${activeNpc.name}`;}try{const r=await store.request('memory',{npc:activeNpc.id,personal:true,offset:historyOffset}),fragment=document.createDocumentFragment();for(const m of r.memories){const wrap=document.createElement('div');appendBubble(wrap,m.playerName||player.name,m.message,true);appendBubble(wrap,activeNpc.name,m.response);fragment.append(wrap);}if(reset&&!r.memories.length)$('history-content').textContent='Your story together is just beginning.';else $('history-content').prepend(fragment);historyOffset+=r.memories.length;$('history-earlier').hidden=!r.hasMore;if(reset)$('history-content').scrollTop=$('history-content').scrollHeight;}catch(e){toast(e.message);}}
function showPack(){const inv=$('inventory');inv.replaceChildren();for(const [kind,symbol]of Object.entries({wood:'▥',stone:'◆',berries:'●',fiber:'≋'})){const item=document.createElement('div'),icon=document.createElement('span'),name=document.createElement('span'),count=document.createElement('b');icon.className='item-icon';icon.textContent=symbol;name.textContent=kind[0].toUpperCase()+kind.slice(1);count.textContent=player.inventory[kind];item.append(icon,name,count);inv.append(item);}
 $('journey-summary').textContent=`${player.visited.length} settlements visited · ${Object.keys(player.caves).length} dungeons entered · ${(player.distance/1000).toFixed(2)} km walked`;$('journal').replaceChildren();for(const e of events.filter(e=>e.type!=='move').slice(0,12)){const div=document.createElement('div');div.className='journal-entry';div.textContent=e.summary;const t=document.createElement('small');t.textContent=new Date(e.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});div.append(t);$('journal').append(div);}openDialog('pack-dialog');}
function redrawMap(){if(world.cave){drawCaveMap($('atlas'),world.cave,{...player,dungeon:{...player.dungeon,x:world.player.x,z:world.player.z}},{detailed:true,depleted:world.depleted,heading:world.hero.rotation.y});$('map-scale').textContent='Dungeon layout';$('map-caption').textContent='Faint rooms are unexplored. Gold dots are supplies; teal marks the stairs.';return;}
 if(!mapCenter)mapCenter={x:world.player.x,z:world.player.z};drawMap($('atlas'),mapCenter,mapSpan,world.player,{detailed:true,waypoint,visited:player.visited,home:player.house});$('map-scale').textContent=`${(mapSpan/1000).toFixed(1)} km across`;$('map-caption').textContent='Diamonds mark ancient ruins. The house marks your cottage. Click to set a waypoint.';
}
async function loadWorld(){
 status('Returning home');let r=await store.request('state');player=r.player;const home=await store.action({type:'return-home'},player);player=home.player;r=await store.request('state');world.setPlayer(player);applySnapshot(r);loaded=true;trail=[];dirty=false;updateUI();$('loading').hidden=true;saved();
 if(store.mode==='local'){$('connection-notice').hidden=false;$('local-options').hidden=false;$('storage-explanation').textContent='Local preview: your home, supplies, dungeon progress, and NPC memories are saved in this browser. Shared account saves need the backend connection.';}else{$('storage-explanation').textContent='Your home and traveler are saved in the shared world. Sign in with the same account on another device to return.';$('signout-button').hidden=false;}
 if(!player.introduced){$('welcome-village').textContent=player.house.villageName;$('traveler-name').value=player.name==='Traveler'?'':player.name;openDialog('welcome');}
 clearInterval(saveTimer);clearInterval(syncTimer);saveTimer=setInterval(flush,2000);syncTimer=setInterval(sync,6500);
}
async function boot(){try{world=new WorldRenderer($('scene'),{onWalk:walk,onFrame:frame});await store.init();if(!store.signedIn){$('loading').hidden=true;openDialog('auth-dialog');return;}await loadWorld();}catch(e){$('loading-text').textContent=e.message;const b=document.createElement('button');b.textContent='Try again';b.onclick=()=>location.reload();$('loading').append(b);}}
$('begin-button').onclick=async()=>{try{await act({type:'rename',name:$('traveler-name').value||'Traveler'});$('welcome').close();toast('A cottage of your own. A whole world beyond its door.');}catch{}};
$('interact-button').onclick=interact;$('eat-button').onclick=()=>act({type:'eat'}).catch(()=>{});$('drink-button').onclick=()=>act({type:'drink'}).catch(()=>{});$('rest-button').onclick=()=>act({type:'rest'}).catch(()=>{});
$('pack-button').onclick=async()=>{await sync();showPack();};$('map-button').onclick=()=>{mapCenter={x:world.player.x,z:world.player.z};for(const id of ['map-minus','map-plus','map-home'])$(id).hidden=!!world.cave;openDialog('map-dialog');redrawMap();};$('account-button').onclick=()=>openDialog('account-dialog');
$('map-minus').onclick=()=>{mapSpan=Math.min(18000,mapSpan*1.5);redrawMap();};$('map-plus').onclick=()=>{mapSpan=Math.max(650,mapSpan/1.5);redrawMap();};$('map-center').onclick=()=>{mapCenter={x:world.player.x,z:world.player.z};redrawMap();};$('map-home').onclick=()=>{mapCenter={x:player.house.x,z:player.house.z};waypoint={x:player.house.doorX,z:player.house.doorZ};redrawMap();};
$('atlas').onclick=e=>{if(world.cave)return;const c=$('atlas'),r=c.getBoundingClientRect();waypoint={x:Math.max(-LIMIT,Math.min(LIMIT,mapCenter.x+((e.clientX-r.left)/r.width-.5)*mapSpan)),z:Math.max(-LIMIT,Math.min(LIMIT,mapCenter.z+((e.clientY-r.top)/r.height-.5)*mapSpan*c.height/c.width))};redrawMap();$('map-caption').textContent=`Waypoint set: ${Math.round(waypoint.x)}, ${Math.round(waypoint.z)}.`;};
$('chat-form').onsubmit=e=>{e.preventDefault();speak($('chat-input').value.trim());};for(const b of $('dialogue-choices').children)b.onclick=()=>speak(b.dataset.line);
$('history-button').onclick=()=>{openDialog('history-dialog');loadHistory(true);};$('history-earlier').onclick=()=>loadHistory();
$('stay-button').onclick=()=>$('entrance-dialog').close();$('enter-button').onclick=async()=>{if(!entrance)return;$('enter-button').disabled=true;try{await act({type:entrance.type==='exit'?'leave-dungeon':'enter-dungeon',target:entrance.id});$('entrance-dialog').close();await sync();}catch{}finally{$('enter-button').disabled=false;}};
$('rename-button').onclick=()=>act({type:'rename',name:$('rename-input').value}).catch(()=>{});$('quality-button').onclick=()=>{$('quality-button').textContent='Quality: '+world.setQuality();};
$('export-button').onclick=async()=>{try{await waitForSave();const a=document.createElement('a'),url=URL.createObjectURL(new Blob([store.exportLocal()],{type:'application/json'}));a.href=url;a.download='evermere-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){toast(e.message);}};
$('import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>10*1024*1024){toast('This save file is too large.');return;}try{store.importLocal(await f.text());location.reload();}catch(e){toast(e.message);}};
async function authenticate(signup=false){$('auth-error').textContent='';if(!$('auth-form').reportValidity())return;$('login-button').disabled=$('signup-button').disabled=true;try{const session=await store.login($('email').value,$('password').value,signup);if(!session){$('auth-error').textContent='Check your email to confirm your account, then sign in.';return;}$('auth-dialog').close();$('loading').hidden=false;await loadWorld();}catch(e){$('auth-error').textContent=e.message;}finally{$('login-button').disabled=$('signup-button').disabled=false;}}
$('auth-form').onsubmit=e=>{e.preventDefault();authenticate();};$('signup-button').onclick=()=>authenticate(true);$('signout-button').onclick=async()=>{try{await waitForSave();await store.logout();location.reload();}catch(e){toast(e.message);}};
window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName)||document.querySelector('dialog[open]')||!loaded)return;if(e.code==='KeyE')interact();if(e.code==='KeyI')showPack();if(e.code==='KeyM')$('map-button').click();});
window.addEventListener('visibilitychange',()=>{if(document.hidden){world.keys={};flush();}});window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}});
const ctx=document.modelContext;if(ctx?.registerTool){const life=new AbortController();const tools=[
 {name:'read_traveler',description:'Read current traveler, nearby interaction, and persistence mode.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({player,nearby:nearby?{id:nearby.id,type:nearby.type}:null,mode:store.mode})},
 {name:'gather_nearby_resource',description:'Gather and save the resource within reach.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async()=>{if(nearby?.type!=='resource')throw Error('No resource within reach.');const r=await act({type:'gather',target:nearby.id});return {summary:r.summary,inventory:player.inventory};}},
 {name:'speak_to_nearby_npc',description:'Send and remember a message to the NPC within reach.',inputSchema:{type:'object',properties:{message:{type:'string',minLength:1,maxLength:800}},required:['message'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(typeof input?.message!=='string'||!input.message.trim()||input.message.length>800)throw Error('Write a message of 1–800 characters.');if(nearby?.type!=='npc')throw Error('No person within reach.');const r=await act({type:'talk',target:nearby.id,message:input.message});if(activeNpc?.id===nearby.id)showLine(r.extra.response);return {response:r.extra.response,saved:true};}}
];for(const tool of tools)try{Promise.resolve(ctx.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>life.abort(),{once:true});}
boot();
